import "./globals.css";
import GlobalLoaderProvider from "@/components/GlobalLoader";
import { Onest } from "next/font/google";

const onest = Onest({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "TransExpert",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <GlobalLoaderProvider minMs={2500}>{children}</GlobalLoaderProvider>
      </body>
    </html>
    
  );
}
